variables:
  TG_URL: 'https://api.telegram.org/${TG_TOKEN}'

build-backend-code-job:
  stage: build  
  only:
    changes:
    - backend/**/*
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=./.m2/repository
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
  cache:
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository

semgrep-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  needs:
    - build-backend-code-job

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/backend/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - backend/.sonar/cache
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true 
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_BACK}
      -Dsonar.projectName=${SONAR_PROJECT_KEY_BACK}
  allow_failure: true
  needs:
    - build-backend-code-job

telegram-notification-backend:
  stage: notify
  only:
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl --request POST --header "Content-Type: application/json" --data "{\"chat_id\": \"-1002185373712\", \"text\": \"Артём Кононюк - бэкенд + SonarQube. Ссылка $CI_PROJECT_URL/-/jobs/artifacts/$CI_COMMIT_SHA/download?job=build-backend-code-job\"}" $TG_URL/sendMessage'
  needs:
    - build-backend-code-job
